"""Searchable beginner guidance. Suggestions never change OBS settings."""
ARTICLES = [
 ('first-stream', 'Your first stream', 'Connect OBS in Connections using its WebSocket password. Pair with your Hub once, link Twitch, YouTube or Kick there, and Sync linked accounts. Add secondary destinations with the platform dropdown and stream keys. Choose your microphone in Audio Guard. Run preflight, send a test chat message, then check picture and sound in each platform dashboard. Start All only starts when you click and confirm.'),
 ('empty-chat', 'Chat is empty', 'Read Connections first. Expired authorization: reconnect that platform in Hub Settings, then Sync. YouTube: start a broadcast with chat enabled on the linked channel; refresh broadcasts and select it. Kick: subscription ready means subscribed, not delivered. Send a fresh message; if absent, the website operator must check webhook signatures, receipt and the relay. Twitch event scopes are separate from chat access. Check platform and channel filters in the OBS Chat dock.'),
 ('audio', 'Viewers cannot hear me', 'Choose the expected microphone and game audio in Audio Guard. Check mute, source activity, and whether the source is on the stream audio track. Quiet scenes intentionally suppress warnings. Record a short local test and listen back, then check the platform dashboard. Meter activity alone cannot verify the final sound. Windows Do Not Disturb can hide notification banners; test the custom chirp separately.'),
 ('frames', 'Frames are dropping', 'Network drops: check wired connection, upload headroom, ingest and competing uploads. Rendering lag: reduce heavy sources or game GPU load, cap game FPS and check scene complexity. Encoding lag: lower encoder workload and review resolution/FPS. Stream Doctor identifies sustained symptoms, not a proven hardware fault. Use Balanced or Relaxed if brief fluctuations are distracting.'),
 ('outputs', 'One platform did not start', 'Open Multistream or Destinations and read that output’s error. Confirm stream key and ingest, and H.264 video/AAC audio on the main OBS stream. Secondary outputs share that encoder; independent resolutions, vertical canvases and Enhanced Broadcasting are not supported here. Retry the failed destination individually. Viewer playback must still be checked on the platform.'),
 ('settings', 'Choose a starting setup', 'Start with OBS Tools → Auto-Configuration Wizard. Choose a conservative resolution and frame rate that your game and encoder can sustain, then do a short test. Hardware alone cannot choose a safe bitrate; measured upload, game load and platform limits also matter. FDGCast does not change your OBS settings. Use the bandwidth calculator in Tools for local multistream headroom.'),
 ('docks', 'Move and customize docks', 'Unlock docks in OBS, drag by the title bar, and drop on an edge or beside another dock. The ⋮ menu saves compact spacing, font size, timestamp and identity options per dock. Chat has platform/channel filters and Jump to latest. Appearance → Reset restores that dock’s defaults without changing stream settings. Today’s Events is optional in the OBS Docks menu.'),
 ('permissions', 'Permissions and Google approval', 'A platform login can authorize chat while event or moderation permissions remain missing. Twitch follows need moderator:read:followers; redeems need channel:read:redemptions and channel-point eligibility. Twitch deletion and bans need separate moderation scopes. YouTube replies/moderation need youtube.force-ssl or youtube and the appropriate channel role. Google branding verification is separate; expired tokens must be refreshed by the Hub.'),
 ('updates', 'Install, update and recover', 'Use the Windows x64 installer with OBS 32.2.2. Close OBS and Companion before upgrading. The app keeps pairing and saved settings. OBS opens Companion automatically; Open app restores its desktop window. Updates are downloaded only when you choose. If a new build fails, close both apps and reinstall the previous installer; preserve your saved settings and export diagnostics before asking for help.'),
 ('overlays', 'Show chat on stream', 'The private OBS chat dock is for you. Enable an optional overlay in Tools and add its separate local URL as an OBS Browser Source. Anyone with that URL can read the selected public chat while Companion runs; it cannot control OBS or retrieve account tokens. Use Selected messages mode to display only messages you highlight. Show immediately or queue messages to display one after another. Rotate the overlay link to revoke the old one. Moderation removes messages from future overlay refreshes.'),
 ('hub', 'Plan with your collaborators', 'The Hub tab and optional Today’s Events dock show owned or accepted events returned by your paired Hub. Times use your local timezone. Select an event for preflight context; this does not start a stream or update platform titles. Accepted RSVP names are commitments, not verified live status. Use the Hub for full schedule editing.'),
 ('integrations', 'Other creator tools', 'OBS WebSocket remains the supported control interface for Streamer.bot and Stream Deck. Connect those tools to OBS using their official setup instructions; do not share FDGCast pairing or platform tokens. Existing alert services can use their own OBS Browser Sources. Calendar export and Crowd Control event links remain in the Hub. Dedicated FDGCast integrations are not shipped in this build.'),
 ('youtube', 'YouTube chat quota', 'YouTube chat uses a persistent streaming connection, not repeated polling. API quota belongs to the shared Google developer project. If it runs out, chat waits for the midnight Pacific reset; logging in again does not restore it. Keep clients updated, and request more project quota before expanding public usage. Sending messages and other API actions also consume quota.'),
 ('audio-test', 'Check audio before going live', 'In Tools, record a short OBS test and listen to the saved file. Existing streaming or recording blocks the test. It uses current OBS recording settings and only stops the recording it started on the same connection. Use the listening checklist; platform and VOD audio still need a real playback check.'),
 ('backup', 'Save preferences', 'Download a preference backup from Tools. Review and restore it only with OBS closed, then restart Companion. Credentials, stream keys, custom sounds, audio source assignments and OBS dock layouts are excluded. New destination names need stream setup before use.'),
 ('support', 'Report a problem or suggest a feature', 'Open Stream Doctor to preview and download diagnostics. They omit chat contents, stream keys and access tokens; output names can still reveal personal details, so review them. Include the installed version, platform, what you expected, what happened and reproduction steps. GitHub issues are public: never paste pairing codes, OAuth credentials or private event details. Live platform delivery needs a real-account test; simulated events are clearly labelled.')
]
LINKS = [
 ('OBS quick start', 'https://obsproject.com/kb/quick-start-guide'),
 ('OBS audio troubleshooting', 'https://obsproject.com/kb/audio-mixer-guide'),
 ('OBS performance troubleshooting', 'https://obsproject.com/kb/encoding-performance-troubleshooting'),
 ('FDGCast issues / feature requests', 'https://github.com/Dakotalamb/ForgeCast/issues'),
 ('FDGCast release notes', 'https://github.com/Dakotalamb/ForgeCast/blob/main/docs/RELEASE_0.8.0.md')
]
